window.BENCHMARK_DATA = {
  "lastUpdate": 1739821999290,
  "repoUrl": "https://github.com/dbus2/zbus",
  "entries": {
    "Benchmark": [
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "84ce1043802a85bd6262c24c40cbb96576cc079a",
          "message": "⬆️ micro: Update winnow to v0.7.2 (#1254)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [winnow](https://redirect.github.com/winnow-rs/winnow) | dependencies\n| patch | `0.7.1` -> `0.7.2` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>winnow-rs/winnow (winnow)</summary>\n\n###\n[`v0.7.2`](https://redirect.github.com/winnow-rs/winnow/blob/HEAD/CHANGELOG.md#072---2025-02-10)\n\n[Compare\nSource](https://redirect.github.com/winnow-rs/winnow/compare/v0.7.1...v0.7.2)\n\n##### Fixes\n\n-   Make `Range` `Copy`able\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xNjQuMSIsInVwZGF0ZWRJblZlciI6IjM5LjE2NC4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-02-10T16:40:23Z",
          "tree_id": "3326aaede4601cdf4752ed0bfbd2ef5c1cd561d2",
          "url": "https://github.com/dbus2/zbus/commit/84ce1043802a85bd6262c24c40cbb96576cc079a"
        },
        "date": 1739206299400,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2217,
            "range": "± 19",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3142048,
            "range": "± 16974",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 280,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3989460,
            "range": "± 17347",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 428,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 493,
            "range": "± 11",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 161,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 156,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 170,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 133,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 133,
            "range": "± 8",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 105,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 215934,
            "range": "± 9256",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 412883,
            "range": "± 7300",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 643540,
            "range": "± 2814",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2062093,
            "range": "± 8681",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 1907878,
            "range": "± 9234",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 3941729,
            "range": "± 41851",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 167940,
            "range": "± 797",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1120317,
            "range": "± 4089",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11067,
            "range": "± 118",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 102,
            "range": "± 2",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "560404895fc92e2ced07a56166d351c47a9a4f1a",
          "message": "Merge pull request #1253 from jasger9000/main\n\n🐛 zv: fix wrong lifetime when creating a Value from &Vec and &[]",
          "timestamp": "2025-02-11T20:20:37+01:00",
          "tree_id": "c260235f493191260be6b8d14d56aef7e5864d2c",
          "url": "https://github.com/dbus2/zbus/commit/560404895fc92e2ced07a56166d351c47a9a4f1a"
        },
        "date": 1739302343676,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2185,
            "range": "± 30",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3289045,
            "range": "± 91254",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 244,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4021805,
            "range": "± 40882",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 422,
            "range": "± 7",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 494,
            "range": "± 15",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 152,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 165,
            "range": "± 8",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 134,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 134,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 77,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 230526,
            "range": "± 15085",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 445917,
            "range": "± 31592",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 751192,
            "range": "± 47701",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2304003,
            "range": "± 123879",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 1996447,
            "range": "± 195605",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4005983,
            "range": "± 26807",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 168743,
            "range": "± 3044",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1116762,
            "range": "± 12664",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10875,
            "range": "± 41",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 102,
            "range": "± 1",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "062a938fdc36aea9e6b9cbbdd0a866a37d46bf8a",
          "message": "⬆️ micro: Update clap to v4.5.29 (#1255)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [clap](https://redirect.github.com/clap-rs/clap) | dependencies |\npatch | `4.5.28` -> `4.5.29` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>clap-rs/clap (clap)</summary>\n\n###\n[`v4.5.29`](https://redirect.github.com/clap-rs/clap/blob/HEAD/CHANGELOG.md#4529---2025-02-11)\n\n[Compare\nSource](https://redirect.github.com/clap-rs/clap/compare/v4.5.28...v4.5.29)\n\n##### Fixes\n\n- Change `ArgMatches::args_present` so not-present flags are considered\nnot-present (matching the documentation)\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xNjQuMSIsInVwZGF0ZWRJblZlciI6IjM5LjE2NC4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-02-11T23:36:23Z",
          "tree_id": "31f62491724515d8e707136eced67ca23d4af399",
          "url": "https://github.com/dbus2/zbus/commit/062a938fdc36aea9e6b9cbbdd0a866a37d46bf8a"
        },
        "date": 1739317657917,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2293,
            "range": "± 176",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3241228,
            "range": "± 32306",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 254,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3962848,
            "range": "± 50449",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 416,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 492,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 152,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 157,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 162,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 131,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 133,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 94,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 214476,
            "range": "± 2238",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 412358,
            "range": "± 3450",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 644412,
            "range": "± 5269",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2088225,
            "range": "± 7661",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 1782123,
            "range": "± 12639",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4067648,
            "range": "± 31274",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 167030,
            "range": "± 766",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1118140,
            "range": "± 5564",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10810,
            "range": "± 99",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 101,
            "range": "± 2",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "cf401c0e47e6d808b6edcfcec7428573f06eb82d",
          "message": "Merge pull request #1256 from zeenix/issue-1252\n\n🐛 zd: Prefix a local variable w/ `__` so it doesn't conflict w/ fields",
          "timestamp": "2025-02-13T11:56:37+01:00",
          "tree_id": "4f0e18a58437c4327f216c305f58c7afab9820b6",
          "url": "https://github.com/dbus2/zbus/commit/cf401c0e47e6d808b6edcfcec7428573f06eb82d"
        },
        "date": 1739444872681,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2190,
            "range": "± 56",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3129478,
            "range": "± 33346",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 268,
            "range": "± 9",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3977215,
            "range": "± 56928",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 424,
            "range": "± 10",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 489,
            "range": "± 14",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 151,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 163,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 127,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 128,
            "range": "± 10",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 76,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 214131,
            "range": "± 1569",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 416953,
            "range": "± 2054",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 617896,
            "range": "± 5820",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2083415,
            "range": "± 5719",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 1782574,
            "range": "± 22518",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 3936233,
            "range": "± 23857",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 169083,
            "range": "± 867",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1138070,
            "range": "± 2406",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11147,
            "range": "± 60",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 100,
            "range": "± 3",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "463e4d54ef8a5324296f5cc3d509cf62b477895a",
          "message": "Merge pull request #540 from katyo/derive-value-enum\n\n✨ zd,zv: `Value` derive improvements for enums",
          "timestamp": "2025-02-14T19:09:50+01:00",
          "tree_id": "a6ba7935264a7f8b004d367593d9e915b2785158",
          "url": "https://github.com/dbus2/zbus/commit/463e4d54ef8a5324296f5cc3d509cf62b477895a"
        },
        "date": 1739557266331,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2275,
            "range": "± 21",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3164758,
            "range": "± 33663",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 254,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4012035,
            "range": "± 12479",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 419,
            "range": "± 27",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 492,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 151,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 162,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 163,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 132,
            "range": "± 10",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 133,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 75,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 223698,
            "range": "± 808",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 412483,
            "range": "± 4286",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 661710,
            "range": "± 35661",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2073877,
            "range": "± 11788",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 1765833,
            "range": "± 3175",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 3932239,
            "range": "± 22344",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 166891,
            "range": "± 1763",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1138622,
            "range": "± 19778",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10943,
            "range": "± 20",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 102,
            "range": "± 2",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "5b70cb85e0b7bf44888ea4904ecdadc660e4cde6",
          "message": "Merge pull request #1257 from dbus2/renovate/tempfile-3.x-lockfile\n\n⬆️ Update tempfile to v3.17.0",
          "timestamp": "2025-02-17T16:46:07+01:00",
          "tree_id": "bd33e7dd7dae39935da60cd25bc6710938e399ad",
          "url": "https://github.com/dbus2/zbus/commit/5b70cb85e0b7bf44888ea4904ecdadc660e4cde6"
        },
        "date": 1739807842673,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2227,
            "range": "± 152",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3161528,
            "range": "± 27573",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 260,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3954554,
            "range": "± 48590",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 421,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 490,
            "range": "± 10",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 152,
            "range": "± 7",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 163,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 133,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 134,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 76,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 217733,
            "range": "± 1516",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 412708,
            "range": "± 1854",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 644059,
            "range": "± 2241",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2091148,
            "range": "± 16133",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 1784027,
            "range": "± 6860",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4071094,
            "range": "± 16872",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 167414,
            "range": "± 443",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1139769,
            "range": "± 2790",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11021,
            "range": "± 32",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 114,
            "range": "± 2",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "f00f91630cd7def536df5452a7d7aea97a4c41c3",
          "message": "⬆️ micro: Update tempfile to v3.17.1 (#1259)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [tempfile](https://stebalien.com/projects/tempfile-rs/)\n([source](https://redirect.github.com/Stebalien/tempfile)) |\ndev-dependencies | patch | `3.17.0` -> `3.17.1` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>Stebalien/tempfile (tempfile)</summary>\n\n###\n[`v3.17.1`](https://redirect.github.com/Stebalien/tempfile/blob/HEAD/CHANGELOG.md#3171)\n\n[Compare\nSource](https://redirect.github.com/Stebalien/tempfile/compare/v3.17.0...v3.17.1)\n\n- Fix build with `windows-sys` 0.52. Unfortunately, we have no CI for\nolder `windows-sys` versions at the moment...\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xNjcuMSIsInVwZGF0ZWRJblZlciI6IjM5LjE2Ny4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-02-17T19:41:51Z",
          "tree_id": "7135c95aa9a943442358c04333df1aecca3c7f2f",
          "url": "https://github.com/dbus2/zbus/commit/f00f91630cd7def536df5452a7d7aea97a4c41c3"
        },
        "date": 1739821997738,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2283,
            "range": "± 47",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3237687,
            "range": "± 123698",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 252,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4040422,
            "range": "± 24490",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 414,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 514,
            "range": "± 10",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 151,
            "range": "± 7",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 164,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 133,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 133,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 75,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 218284,
            "range": "± 1713",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 412631,
            "range": "± 1564",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 642975,
            "range": "± 9812",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2107644,
            "range": "± 40419",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 1821333,
            "range": "± 5451",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4100697,
            "range": "± 54467",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 169620,
            "range": "± 3411",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1144493,
            "range": "± 28971",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10980,
            "range": "± 76",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 114,
            "range": "± 2",
            "unit": "ns/iter"
          }
        ]
      }
    ]
  }
}