window.BENCHMARK_DATA = {
  "lastUpdate": 1754397768227,
  "repoUrl": "https://github.com/dbus2/zbus",
  "entries": {
    "Benchmark": [
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "cdad66ec1ce1acb26a96332a2fd7fb31b8054a91",
          "message": "⬆️ micro: Update serde_json to v1.0.141 (#1436)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [serde_json](https://redirect.github.com/serde-rs/json) |\nworkspace.dependencies | patch | `1.0.140` -> `1.0.141` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>serde-rs/json (serde_json)</summary>\n\n###\n[`v1.0.141`](https://redirect.github.com/serde-rs/json/releases/tag/v1.0.141)\n\n[Compare\nSource](https://redirect.github.com/serde-rs/json/compare/v1.0.140...v1.0.141)\n\n- Optimize string escaping during serialization\n([#&#8203;1273](https://redirect.github.com/serde-rs/json/issues/1273),\nthanks\n[@&#8203;conradludgate](https://redirect.github.com/conradludgate))\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4yMy4yIiwidXBkYXRlZEluVmVyIjoiNDEuMjMuMiIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-07-18T23:35:57Z",
          "tree_id": "f8ca1ce005e8bfc49ffa23f7b80b89b68e2afdf4",
          "url": "https://github.com/dbus2/zbus/commit/cdad66ec1ce1acb26a96332a2fd7fb31b8054a91"
        },
        "date": 1752882440020,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2154,
            "range": "± 146",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3175710,
            "range": "± 12942",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 252,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3959186,
            "range": "± 14004",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 425,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 536,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 157,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 157,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 167,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 134,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 132,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 94,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 424654,
            "range": "± 15924",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 475336,
            "range": "± 1957",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1177589,
            "range": "± 3654",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2237176,
            "range": "± 17545",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2291539,
            "range": "± 10708",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4366580,
            "range": "± 18014",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 968895,
            "range": "± 4774",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1280965,
            "range": "± 6615",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11343,
            "range": "± 135",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 92,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "97d5818fdcc4370506b8613f8f608ff9530fed25",
          "message": "⬆️ micro: Update rand to v0.9.2 (#1438)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [rand](https://rust-random.github.io/book)\n([source](https://redirect.github.com/rust-random/rand)) |\nworkspace.dependencies | patch | `0.9.1` -> `0.9.2` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>rust-random/rand (rand)</summary>\n\n###\n[`v0.9.2`](https://redirect.github.com/rust-random/rand/blob/HEAD/CHANGELOG.md#092--2025-07-20)\n\n##### Deprecated\n\n- Deprecate `rand::rngs::mock` module and `StepRng` generator\n([#&#8203;1634](https://redirect.github.com/rust-random/rand/issues/1634))\n\n##### Additions\n\n- Enable `WeightedIndex<usize>` (de)serialization\n([#&#8203;1646](https://redirect.github.com/rust-random/rand/issues/1646))\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4yMy4yIiwidXBkYXRlZEluVmVyIjoiNDEuMjMuMiIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-07-20T18:22:29Z",
          "tree_id": "1b8521b012407ee95df0a1900d10bc4b0bf24dce",
          "url": "https://github.com/dbus2/zbus/commit/97d5818fdcc4370506b8613f8f608ff9530fed25"
        },
        "date": 1753036431655,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2133,
            "range": "± 115",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3176146,
            "range": "± 11954",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 219,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4335440,
            "range": "± 8478",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 395,
            "range": "± 24",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 495,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 158,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 162,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 167,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 135,
            "range": "± 8",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 137,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 76,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 535680,
            "range": "± 5345",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 464115,
            "range": "± 2818",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1202322,
            "range": "± 6144",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2129967,
            "range": "± 8877",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2368535,
            "range": "± 23029",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4103210,
            "range": "± 24048",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 970138,
            "range": "± 1081",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1270491,
            "range": "± 2895",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10977,
            "range": "± 32",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 93,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "2735b3c09f8fa47e5ba6268dd5bf28bfd2dfdc52",
          "message": "Merge pull request #1102 from dbus2/renovate/quick-xml-0.x\n\n⬆️ Update quick-xml to 0.38",
          "timestamp": "2025-07-21T13:32:30+02:00",
          "tree_id": "d63ad76c3cbaf323cf7b8e84ee69d7b77a5d7a14",
          "url": "https://github.com/dbus2/zbus/commit/2735b3c09f8fa47e5ba6268dd5bf28bfd2dfdc52"
        },
        "date": 1753098223544,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2202,
            "range": "± 61",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3184084,
            "range": "± 24282",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 212,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4162025,
            "range": "± 19751",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 406,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 491,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 152,
            "range": "± 13",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 156,
            "range": "± 7",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 162,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 135,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 135,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 94,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 422040,
            "range": "± 7065",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 453811,
            "range": "± 2148",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1220152,
            "range": "± 5736",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2143083,
            "range": "± 9367",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2352905,
            "range": "± 9704",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4231339,
            "range": "± 14665",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 1034700,
            "range": "± 1082",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1287553,
            "range": "± 10146",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11112,
            "range": "± 151",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 84,
            "range": "± 1",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "9fd627097b773dec82cb8f014acbe9e89c7610af",
          "message": "Merge pull request #1407 from dbus2/renovate/windows-sys-0.x\n\n⬆️ Update windows-sys to 0.60",
          "timestamp": "2025-07-21T14:39:35+02:00",
          "tree_id": "ebb46a583a2aeac21d214337732e08aa0e70f75f",
          "url": "https://github.com/dbus2/zbus/commit/9fd627097b773dec82cb8f014acbe9e89c7610af"
        },
        "date": 1753102255535,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2145,
            "range": "± 24",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3189805,
            "range": "± 24536",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 214,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4305935,
            "range": "± 44196",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 408,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 497,
            "range": "± 33",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 151,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 7",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 162,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 135,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 133,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 95,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 426220,
            "range": "± 4416",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 454165,
            "range": "± 3111",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1231052,
            "range": "± 6817",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2127618,
            "range": "± 13560",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2374947,
            "range": "± 12990",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4058490,
            "range": "± 11112",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 1034698,
            "range": "± 1461",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1288596,
            "range": "± 4659",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11148,
            "range": "± 17",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 84,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "8ee64c6e6af1e40e74d2306b95e66a9170328f0c",
          "message": "Merge pull request #1441 from dbus2/renovate/criterion-0.x\n\n⬆️ Update criterion to 0.7.0",
          "timestamp": "2025-07-25T15:19:49+02:00",
          "tree_id": "79f88be69b502836c7469f11e88ff75d01e41b5c",
          "url": "https://github.com/dbus2/zbus/commit/8ee64c6e6af1e40e74d2306b95e66a9170328f0c"
        },
        "date": 1753450269497,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2209,
            "range": "± 30",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3663899,
            "range": "± 77138",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 221,
            "range": "± 13",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4000863,
            "range": "± 40260",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 431,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 523,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 157,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 156,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 167,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 136,
            "range": "± 8",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 137,
            "range": "± 0",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 76,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 382012,
            "range": "± 14086",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 453567,
            "range": "± 1303",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1119574,
            "range": "± 6676",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2145110,
            "range": "± 9095",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2276868,
            "range": "± 8826",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4190629,
            "range": "± 14812",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 969162,
            "range": "± 4944",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1281074,
            "range": "± 4728",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11204,
            "range": "± 63",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 93,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "4e1c9a248a1916200735be44ec1081e8ec4677de",
          "message": "Merge pull request #1440 from A6GibKm/zv-value-into-owned\n\n✨ zv: Add `ObjectPath::into` owned and `OwnedValue::try_from::<Value>`",
          "timestamp": "2025-07-25T16:25:40+02:00",
          "tree_id": "f3717ff4c93198cb918692f9929c725ddb23c339",
          "url": "https://github.com/dbus2/zbus/commit/4e1c9a248a1916200735be44ec1081e8ec4677de"
        },
        "date": 1753454216808,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2196,
            "range": "± 24",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3659130,
            "range": "± 21916",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 229,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3977678,
            "range": "± 9546",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 417,
            "range": "± 23",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 523,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 151,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 162,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 135,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 133,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 101,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 421170,
            "range": "± 2145",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 458468,
            "range": "± 4230",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1123715,
            "range": "± 5257",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2124877,
            "range": "± 3790",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2252641,
            "range": "± 6465",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 3989492,
            "range": "± 5461",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 1000039,
            "range": "± 1881",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1266434,
            "range": "± 1107",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10827,
            "range": "± 117",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 85,
            "range": "± 1",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "6da6b1b5f528fe2d14b0f25ae1dca1a9fd31575c",
          "message": "Merge pull request #1442 from dbus2/renovate/tokio-1.x-lockfile\n\n⬆️ Update tokio to v1.47.0",
          "timestamp": "2025-07-27T01:45:53+02:00",
          "tree_id": "13c0b6c22bf95f10028414d223cf8b1cfb9d10eb",
          "url": "https://github.com/dbus2/zbus/commit/6da6b1b5f528fe2d14b0f25ae1dca1a9fd31575c"
        },
        "date": 1753574236776,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2299,
            "range": "± 39",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3634844,
            "range": "± 38922",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 223,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3906729,
            "range": "± 19229",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 386,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 500,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 152,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 0",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 163,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 133,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 131,
            "range": "± 0",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 105,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 417820,
            "range": "± 3165",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 456504,
            "range": "± 1616",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1115201,
            "range": "± 3222",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2159190,
            "range": "± 9885",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2411136,
            "range": "± 8996",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 3945304,
            "range": "± 26807",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 1001051,
            "range": "± 5013",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1268198,
            "range": "± 2571",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11077,
            "range": "± 45",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 82,
            "range": "± 1",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "zeenix@gmail.com",
            "name": "Zeeshan Ali Khan",
            "username": "zeenix"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "2c9eafb73b04570df7d7a9660b898f030975ea49",
          "message": "Merge pull request #1426 from KmolYuan/property-yield-current-value\n\n✨ zb: Property stream will yield the current value on the first element",
          "timestamp": "2025-08-05T14:18:54+02:00",
          "tree_id": "2ed0b2d34c5d602fb3a8e52fea38eab46c9f0fcc",
          "url": "https://github.com/dbus2/zbus/commit/2c9eafb73b04570df7d7a9660b898f030975ea49"
        },
        "date": 1754397010778,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2344,
            "range": "± 17",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3570640,
            "range": "± 26310",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 237,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4030079,
            "range": "± 9580",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 404,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 493,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 152,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 162,
            "range": "± 2",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 133,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 133,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 105,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 428889,
            "range": "± 13540",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 453880,
            "range": "± 763",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1246466,
            "range": "± 4711",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2130828,
            "range": "± 6169",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2431611,
            "range": "± 9117",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 3994580,
            "range": "± 15597",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 1000054,
            "range": "± 940",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1301505,
            "range": "± 2460",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10936,
            "range": "± 31",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 131,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "84daaed679add79962494c70f10aa2eb57b96eb1",
          "message": "⬆️ micro: Update async-lock to v3.4.1 (#1443)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [async-lock](https://redirect.github.com/smol-rs/async-lock) |\nworkspace.dependencies | patch | `3.4.0` -> `3.4.1` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>smol-rs/async-lock (async-lock)</summary>\n\n###\n[`v3.4.1`](https://redirect.github.com/smol-rs/async-lock/blob/HEAD/CHANGELOG.md#Version-341)\n\n[Compare\nSource](https://redirect.github.com/smol-rs/async-lock/compare/v3.4.0...v3.4.1)\n\n- Fix typos in docs.\n([#&#8203;89](https://redirect.github.com/smol-rs/async-lock/issues/89))\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS41MS4xIiwidXBkYXRlZEluVmVyIjoiNDEuNTEuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-08-05T12:31:06Z",
          "tree_id": "e0063b94508346bb4e553f3e1dd1948b200a038b",
          "url": "https://github.com/dbus2/zbus/commit/84daaed679add79962494c70f10aa2eb57b96eb1"
        },
        "date": 1754397756312,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2259,
            "range": "± 85",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3662842,
            "range": "± 40691",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 233,
            "range": "± 0",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4454934,
            "range": "± 75608",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 412,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 493,
            "range": "± 9",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 152,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 54",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 162,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 132,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 131,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 105,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 430641,
            "range": "± 10098",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 454170,
            "range": "± 3065",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1254502,
            "range": "± 7556",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2142456,
            "range": "± 7141",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2419683,
            "range": "± 14008",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4010426,
            "range": "± 73730",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 1000945,
            "range": "± 4955",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1282786,
            "range": "± 5631",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11007,
            "range": "± 38",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 131,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "0e2d1bfd0798c0c3b5c37a8e108f11cc88e05077",
          "message": "⬆️ micro: Update clap to v4.5.42 (#1444)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [clap](https://redirect.github.com/clap-rs/clap) |\nworkspace.dependencies | patch | `4.5.41` -> `4.5.42` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>clap-rs/clap (clap)</summary>\n\n###\n[`v4.5.42`](https://redirect.github.com/clap-rs/clap/blob/HEAD/CHANGELOG.md#4542---2025-07-30)\n\n[Compare\nSource](https://redirect.github.com/clap-rs/clap/compare/v4.5.41...v4.5.42)\n\n##### Fixes\n\n- Include subcommand visible long aliases in `--help`\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS41MS4xIiwidXBkYXRlZEluVmVyIjoiNDEuNTEuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-08-05T12:31:26Z",
          "tree_id": "840697bd835d49b2ccc8e7b7b72bc22f5419a167",
          "url": "https://github.com/dbus2/zbus/commit/0e2d1bfd0798c0c3b5c37a8e108f11cc88e05077"
        },
        "date": 1754397766945,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2270,
            "range": "± 12",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3659337,
            "range": "± 19164",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 239,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 4112207,
            "range": "± 37718",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 404,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 491,
            "range": "± 7",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 153,
            "range": "± 19",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 155,
            "range": "± 5",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 163,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 132,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 132,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 105,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 458298,
            "range": "± 25316",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 452115,
            "range": "± 4291",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1299654,
            "range": "± 16556",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2124592,
            "range": "± 10340",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2383544,
            "range": "± 12459",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 3924862,
            "range": "± 20415",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 999985,
            "range": "± 3009",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1281585,
            "range": "± 18366",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 10993,
            "range": "± 21",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 130,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      }
    ]
  }
}