window.BENCHMARK_DATA = {
  "lastUpdate": 1752882441072,
  "repoUrl": "https://github.com/dbus2/zbus",
  "entries": {
    "Benchmark": [
      {
        "commit": {
          "author": {
            "email": "29139614+renovate[bot]@users.noreply.github.com",
            "name": "renovate[bot]",
            "username": "renovate[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "cdad66ec1ce1acb26a96332a2fd7fb31b8054a91",
          "message": "⬆️ micro: Update serde_json to v1.0.141 (#1436)\n\nThis PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [serde_json](https://redirect.github.com/serde-rs/json) |\nworkspace.dependencies | patch | `1.0.140` -> `1.0.141` |\n\n---\n\n### Release Notes\n\n<details>\n<summary>serde-rs/json (serde_json)</summary>\n\n###\n[`v1.0.141`](https://redirect.github.com/serde-rs/json/releases/tag/v1.0.141)\n\n[Compare\nSource](https://redirect.github.com/serde-rs/json/compare/v1.0.140...v1.0.141)\n\n- Optimize string escaping during serialization\n([#&#8203;1273](https://redirect.github.com/serde-rs/json/issues/1273),\nthanks\n[@&#8203;conradludgate](https://redirect.github.com/conradludgate))\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined),\nAutomerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the\nrebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update\nagain.\n\n---\n\n- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check\nthis box\n\n---\n\nThis PR was generated by [Mend Renovate](https://mend.io/renovate/).\nView the [repository job\nlog](https://developer.mend.io/github/dbus2/zbus).\n\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4yMy4yIiwidXBkYXRlZEluVmVyIjoiNDEuMjMuMiIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
          "timestamp": "2025-07-18T23:35:57Z",
          "tree_id": "f8ca1ce005e8bfc49ffa23f7b80b89b68e2afdf4",
          "url": "https://github.com/dbus2/zbus/commit/cdad66ec1ce1acb26a96332a2fd7fb31b8054a91"
        },
        "date": 1752882440020,
        "tool": "cargo",
        "benches": [
          {
            "name": "message-ser/small",
            "value": 2154,
            "range": "± 146",
            "unit": "ns/iter"
          },
          {
            "name": "message-ser/big",
            "value": 3175710,
            "range": "± 12942",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/header",
            "value": 252,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "message-de/body",
            "value": 3959186,
            "range": "± 14004",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/unix",
            "value": 425,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "parse_dbus_address/tcp",
            "value": 536,
            "range": "± 4",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/well_known",
            "value": 157,
            "range": "± 6",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/unique",
            "value": 157,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/bus",
            "value": 167,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/interface",
            "value": 134,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/error",
            "value": 132,
            "range": "± 1",
            "unit": "ns/iter"
          },
          {
            "name": "parse_name/member",
            "value": 94,
            "range": "± 3",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_ser",
            "value": 424654,
            "range": "± 15924",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_de",
            "value": 475336,
            "range": "± 1957",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_ser",
            "value": 1177589,
            "range": "± 3654",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_ass_dict_de",
            "value": 2237176,
            "range": "± 17545",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_ser",
            "value": 2291539,
            "range": "± 10708",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/big_array_and_asv_dict_de",
            "value": 4366580,
            "range": "± 18014",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_ser",
            "value": 968895,
            "range": "± 4774",
            "unit": "ns/iter"
          },
          {
            "name": "dbus/fixed_size_array_de",
            "value": 1280965,
            "range": "± 6615",
            "unit": "ns/iter"
          },
          {
            "name": "signature_parse",
            "value": 11343,
            "range": "± 135",
            "unit": "ns/iter"
          },
          {
            "name": "object_path_parse",
            "value": 92,
            "range": "± 0",
            "unit": "ns/iter"
          }
        ]
      }
    ]
  }
}