[book]
authors = ["Marc-André Lureau", "Zeeshan Ali Khan"]
language = "en"
multilingual = false
src = "src"
title = "zbus: D-Bus for Rust made easy"

[rust]
edition = "2021"

[output.html]
default-theme = "Rust"
smart-punctuation = true
git-repository-url = "https://github.com/z-galaxy/zbus"
edit-url-template = "https://github.com/z-galaxy/zbus/edit/main/book/{path}"
git-repository-icon = "fa-github"
no-section-label = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
